//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DormitoryManagementEntities : DbContext
    {
        public DormitoryManagementEntities()
            : base("name=DormitoryManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DienNuocSuDung> DienNuocSuDungs { get; set; }
        public virtual DbSet<HopDongThuePhong> HopDongThuePhongs { get; set; }
        public virtual DbSet<LoaiNhanVien> LoaiNhanViens { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public virtual DbSet<LoaiTaiKhoan> LoaiTaiKhoans { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<Toa> Toas { get; set; }
        public virtual DbSet<Truong> Truongs { get; set; }
        public virtual DbSet<HoaDonTienDienNuoc> HoaDonTienDienNuocs { get; set; }
        public virtual DbSet<SearchSVToa> SearchSVToas { get; set; }
        public virtual DbSet<SoNVTheoLoaiNV> SoNVTheoLoaiNVs { get; set; }
        public virtual DbSet<SoPhongTrongTheoToa> SoPhongTrongTheoToas { get; set; }
        public virtual DbSet<SV_SPKT> SV_SPKT { get; set; }
        public virtual DbSet<SVHetHopDong2022> SVHetHopDong2022 { get; set; }
        public virtual DbSet<TienPhongMoiSV> TienPhongMoiSVs { get; set; }
        public virtual DbSet<TongSVTheoToa> TongSVTheoToas { get; set; }
    
        [DbFunction("DormitoryManagementEntities", "fn_SearchMaNV")]
        public virtual IQueryable<fn_SearchMaNV_Result> fn_SearchMaNV(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_SearchMaNV_Result>("[DormitoryManagementEntities].[fn_SearchMaNV](@MaNV)", maNVParameter);
        }
    
        [DbFunction("DormitoryManagementEntities", "fn_SearchMaSV")]
        public virtual IQueryable<fn_SearchMaSV_Result> fn_SearchMaSV(string maSinhVien)
        {
            var maSinhVienParameter = maSinhVien != null ?
                new ObjectParameter("MaSinhVien", maSinhVien) :
                new ObjectParameter("MaSinhVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_SearchMaSV_Result>("[DormitoryManagementEntities].[fn_SearchMaSV](@MaSinhVien)", maSinhVienParameter);
        }
    
        [DbFunction("DormitoryManagementEntities", "fn_SearchSVToa")]
        public virtual IQueryable<fn_SearchSVToa_Result> fn_SearchSVToa(string maToa)
        {
            var maToaParameter = maToa != null ?
                new ObjectParameter("MaToa", maToa) :
                new ObjectParameter("MaToa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_SearchSVToa_Result>("[DormitoryManagementEntities].[fn_SearchSVToa](@MaToa)", maToaParameter);
        }
    
        [DbFunction("DormitoryManagementEntities", "fn_SearchTenNV")]
        public virtual IQueryable<fn_SearchTenNV_Result> fn_SearchTenNV(string tenNV)
        {
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_SearchTenNV_Result>("[DormitoryManagementEntities].[fn_SearchTenNV](@TenNV)", tenNVParameter);
        }
    
        [DbFunction("DormitoryManagementEntities", "fn_SearchTenSV")]
        public virtual IQueryable<fn_SearchTenSV_Result> fn_SearchTenSV(string tenSinhVien)
        {
            var tenSinhVienParameter = tenSinhVien != null ?
                new ObjectParameter("TenSinhVien", tenSinhVien) :
                new ObjectParameter("TenSinhVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_SearchTenSV_Result>("[DormitoryManagementEntities].[fn_SearchTenSV](@TenSinhVien)", tenSinhVienParameter);
        }
    
        [DbFunction("DormitoryManagementEntities", "fn_ShowPhongChuaThanhToan")]
        public virtual IQueryable<fn_ShowPhongChuaThanhToan_Result> fn_ShowPhongChuaThanhToan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ShowPhongChuaThanhToan_Result>("[DormitoryManagementEntities].[fn_ShowPhongChuaThanhToan]()");
        }
    
        [DbFunction("DormitoryManagementEntities", "fn_ShowPhongTrong")]
        public virtual IQueryable<fn_ShowPhongTrong_Result> fn_ShowPhongTrong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ShowPhongTrong_Result>("[DormitoryManagementEntities].[fn_ShowPhongTrong]()");
        }
    
        [DbFunction("DormitoryManagementEntities", "fn_ThanhToan")]
        public virtual IQueryable<fn_ThanhToan_Result> fn_ThanhToan(string maPhong)
        {
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ThanhToan_Result>("[DormitoryManagementEntities].[fn_ThanhToan](@MaPhong)", maPhongParameter);
        }
    
        public virtual ObjectResult<string> QL_AuthoLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("QL_AuthoLogin", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_DeleteDienNuoc(string maHoaDon)
        {
            var maHoaDonParameter = maHoaDon != null ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteDienNuoc", maHoaDonParameter);
        }
    
        public virtual int sp_DeleteNhanVien(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteNhanVien", maNVParameter);
        }
    
        public virtual int sp_DeleteSinhVien(string maSinhVien)
        {
            var maSinhVienParameter = maSinhVien != null ?
                new ObjectParameter("MaSinhVien", maSinhVien) :
                new ObjectParameter("MaSinhVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteSinhVien", maSinhVienParameter);
        }
    
        public virtual int sp_DeleteTaiKhoan(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteTaiKhoan", maNVParameter);
        }
    
        public virtual int sp_InsertDienNuoc(string maHoaDon, string maPhong, Nullable<System.DateTime> ngayLap, Nullable<int> soDienTieuThu, Nullable<int> soNuocTieuThu, string trangThai)
        {
            var maHoaDonParameter = maHoaDon != null ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(string));
    
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var soDienTieuThuParameter = soDienTieuThu.HasValue ?
                new ObjectParameter("SoDienTieuThu", soDienTieuThu) :
                new ObjectParameter("SoDienTieuThu", typeof(int));
    
            var soNuocTieuThuParameter = soNuocTieuThu.HasValue ?
                new ObjectParameter("SoNuocTieuThu", soNuocTieuThu) :
                new ObjectParameter("SoNuocTieuThu", typeof(int));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertDienNuoc", maHoaDonParameter, maPhongParameter, ngayLapParameter, soDienTieuThuParameter, soNuocTieuThuParameter, trangThaiParameter);
        }
    
        public virtual int sp_InsertNhanVien(string maNV, string maLoaiNV, string maToa, string tenNV, string soDienThoai, Nullable<int> luong)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maLoaiNVParameter = maLoaiNV != null ?
                new ObjectParameter("MaLoaiNV", maLoaiNV) :
                new ObjectParameter("MaLoaiNV", typeof(string));
    
            var maToaParameter = maToa != null ?
                new ObjectParameter("MaToa", maToa) :
                new ObjectParameter("MaToa", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertNhanVien", maNVParameter, maLoaiNVParameter, maToaParameter, tenNVParameter, soDienThoaiParameter, luongParameter);
        }
    
        public virtual int sp_InsertPhong(string maPhong, string maToa, string maLoaiPhong, string trangThai)
        {
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            var maToaParameter = maToa != null ?
                new ObjectParameter("MaToa", maToa) :
                new ObjectParameter("MaToa", typeof(string));
    
            var maLoaiPhongParameter = maLoaiPhong != null ?
                new ObjectParameter("MaLoaiPhong", maLoaiPhong) :
                new ObjectParameter("MaLoaiPhong", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertPhong", maPhongParameter, maToaParameter, maLoaiPhongParameter, trangThaiParameter);
        }
    
        public virtual int sp_InsertSinhVien(string maSinhVien, string tenSinhVien, string gioiTinh, string soDienThoai, string maTruong, string maPhong)
        {
            var maSinhVienParameter = maSinhVien != null ?
                new ObjectParameter("MaSinhVien", maSinhVien) :
                new ObjectParameter("MaSinhVien", typeof(string));
    
            var tenSinhVienParameter = tenSinhVien != null ?
                new ObjectParameter("TenSinhVien", tenSinhVien) :
                new ObjectParameter("TenSinhVien", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertSinhVien", maSinhVienParameter, tenSinhVienParameter, gioiTinhParameter, soDienThoaiParameter, maTruongParameter, maPhongParameter);
        }
    
        public virtual int sp_InsertTaiKhoan(string maNV, string tenDangnhap, string matKhau, string maLoaiTaiKhoan)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenDangnhapParameter = tenDangnhap != null ?
                new ObjectParameter("TenDangnhap", tenDangnhap) :
                new ObjectParameter("TenDangnhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var maLoaiTaiKhoanParameter = maLoaiTaiKhoan != null ?
                new ObjectParameter("MaLoaiTaiKhoan", maLoaiTaiKhoan) :
                new ObjectParameter("MaLoaiTaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertTaiKhoan", maNVParameter, tenDangnhapParameter, matKhauParameter, maLoaiTaiKhoanParameter);
        }
    
        public virtual int sp_InsertToa(string maToa, Nullable<short> soTang, Nullable<int> sucChua, Nullable<short> soPhongToiDa)
        {
            var maToaParameter = maToa != null ?
                new ObjectParameter("MaToa", maToa) :
                new ObjectParameter("MaToa", typeof(string));
    
            var soTangParameter = soTang.HasValue ?
                new ObjectParameter("SoTang", soTang) :
                new ObjectParameter("SoTang", typeof(short));
    
            var sucChuaParameter = sucChua.HasValue ?
                new ObjectParameter("SucChua", sucChua) :
                new ObjectParameter("SucChua", typeof(int));
    
            var soPhongToiDaParameter = soPhongToiDa.HasValue ?
                new ObjectParameter("SoPhongToiDa", soPhongToiDa) :
                new ObjectParameter("SoPhongToiDa", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertToa", maToaParameter, soTangParameter, sucChuaParameter, soPhongToiDaParameter);
        }
    
        public virtual int sp_UpdateDienNuoc(string maHoaDon, string maPhong, Nullable<System.DateTime> ngayLap, Nullable<int> soDienTieuThu, Nullable<int> soNuocTieuThu, string trangThai)
        {
            var maHoaDonParameter = maHoaDon != null ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(string));
    
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var soDienTieuThuParameter = soDienTieuThu.HasValue ?
                new ObjectParameter("SoDienTieuThu", soDienTieuThu) :
                new ObjectParameter("SoDienTieuThu", typeof(int));
    
            var soNuocTieuThuParameter = soNuocTieuThu.HasValue ?
                new ObjectParameter("SoNuocTieuThu", soNuocTieuThu) :
                new ObjectParameter("SoNuocTieuThu", typeof(int));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateDienNuoc", maHoaDonParameter, maPhongParameter, ngayLapParameter, soDienTieuThuParameter, soNuocTieuThuParameter, trangThaiParameter);
        }
    
        public virtual int sp_UpdateHopDong(string maHD, string maSV, Nullable<System.DateTime> ngayKHD, Nullable<System.DateTime> ngayKTHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var ngayKHDParameter = ngayKHD.HasValue ?
                new ObjectParameter("NgayKHD", ngayKHD) :
                new ObjectParameter("NgayKHD", typeof(System.DateTime));
    
            var ngayKTHDParameter = ngayKTHD.HasValue ?
                new ObjectParameter("NgayKTHD", ngayKTHD) :
                new ObjectParameter("NgayKTHD", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateHopDong", maHDParameter, maSVParameter, ngayKHDParameter, ngayKTHDParameter);
        }
    
        public virtual int sp_UpdatematKhau(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatematKhau", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int sp_UpdateNhanVien(string maNV, string maLoaiNV, string maToa, string tenNV, string soDienThoai, Nullable<int> luong)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maLoaiNVParameter = maLoaiNV != null ?
                new ObjectParameter("MaLoaiNV", maLoaiNV) :
                new ObjectParameter("MaLoaiNV", typeof(string));
    
            var maToaParameter = maToa != null ?
                new ObjectParameter("MaToa", maToa) :
                new ObjectParameter("MaToa", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateNhanVien", maNVParameter, maLoaiNVParameter, maToaParameter, tenNVParameter, soDienThoaiParameter, luongParameter);
        }
    
        public virtual int sp_UpdatePhong(string maPhong, string maToa, string maLoaiPhong, string trangThai)
        {
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            var maToaParameter = maToa != null ?
                new ObjectParameter("MaToa", maToa) :
                new ObjectParameter("MaToa", typeof(string));
    
            var maLoaiPhongParameter = maLoaiPhong != null ?
                new ObjectParameter("MaLoaiPhong", maLoaiPhong) :
                new ObjectParameter("MaLoaiPhong", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatePhong", maPhongParameter, maToaParameter, maLoaiPhongParameter, trangThaiParameter);
        }
    
        public virtual int sp_UpdateSinhVien(string maSinhVien, string tenSinhVien, string gioiTinh, string soDienThoai, string maTruong, string maPhong)
        {
            var maSinhVienParameter = maSinhVien != null ?
                new ObjectParameter("MaSinhVien", maSinhVien) :
                new ObjectParameter("MaSinhVien", typeof(string));
    
            var tenSinhVienParameter = tenSinhVien != null ?
                new ObjectParameter("TenSinhVien", tenSinhVien) :
                new ObjectParameter("TenSinhVien", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var maTruongParameter = maTruong != null ?
                new ObjectParameter("MaTruong", maTruong) :
                new ObjectParameter("MaTruong", typeof(string));
    
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateSinhVien", maSinhVienParameter, tenSinhVienParameter, gioiTinhParameter, soDienThoaiParameter, maTruongParameter, maPhongParameter);
        }
    
        public virtual int sp_UpdateTaiKhoan(string maNV, string tenDangnhap, string maLoaiTaiKhoan)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenDangnhapParameter = tenDangnhap != null ?
                new ObjectParameter("TenDangnhap", tenDangnhap) :
                new ObjectParameter("TenDangnhap", typeof(string));
    
            var maLoaiTaiKhoanParameter = maLoaiTaiKhoan != null ?
                new ObjectParameter("MaLoaiTaiKhoan", maLoaiTaiKhoan) :
                new ObjectParameter("MaLoaiTaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateTaiKhoan", maNVParameter, tenDangnhapParameter, maLoaiTaiKhoanParameter);
        }
    
        public virtual int sp_UpdateThanhToan(string maPhong)
        {
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateThanhToan", maPhongParameter);
        }
    
        public virtual int sp_UpdateToa(string maToa, Nullable<short> soTang, Nullable<int> sucChua, Nullable<short> soPhongToiDa)
        {
            var maToaParameter = maToa != null ?
                new ObjectParameter("MaToa", maToa) :
                new ObjectParameter("MaToa", typeof(string));
    
            var soTangParameter = soTang.HasValue ?
                new ObjectParameter("SoTang", soTang) :
                new ObjectParameter("SoTang", typeof(short));
    
            var sucChuaParameter = sucChua.HasValue ?
                new ObjectParameter("SucChua", sucChua) :
                new ObjectParameter("SucChua", typeof(int));
    
            var soPhongToiDaParameter = soPhongToiDa.HasValue ?
                new ObjectParameter("SoPhongToiDa", soPhongToiDa) :
                new ObjectParameter("SoPhongToiDa", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateToa", maToaParameter, soTangParameter, sucChuaParameter, soPhongToiDaParameter);
        }
    }
}
