//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TienPhongMoiSV
    {
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public string MaPhong { get; set; }
        public string Mã_loại_phòng { get; set; }
        public string Giá_phòng { get; set; }
    }
}
